name: Deploy to Front EC2 instance

on:
  push:
    branches:
      - main
    paths:
      - "front/**"

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies & Build
        working-directory: front
        run: |
          npm install
          echo -e $ENV > .env
          npm run build
          echo $FRONT_SSL_KEY > build/client_key.pem
          echo $FRONT_SSL_CERT > build/client_cert.pem
          echo $BACK_SSL_CERT > build/back_cert.pem
        env:
          ENV: ${{ secrets.EC2_FRONT_ENV }}
          FRONT_SSL_KEY: ${{secrets.EC2_FRONT_SSL_KEY}}
          FRONT_SSL_CERT: ${{secrets.EC2_FRONT_SSL_CERT}}
          BACK_SSL_CERT: ${{secrets.EC2_BACK_SSL_CERT}}

      - name: SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_FRONT_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_FRONT_PRIVATE_KEY }}
          source: "front/build"
          target: "www"
          strip_components: 1
